import type {
  LocationGeoScope,
  LocationMatchStrictness,
  LocationSourceCapabilities,
  LocationSourcePlan,
  LocationWorkplaceType,
} from "../location-domain.js";

export {
  buildLocationEvidence,
  buildLocationPreferencesSummary,
  createLocationIntent,
  createLocationIntentFromLegacyInputs,
  describeLocationIntent,
  getCompatibleSourcesForLocationIntent,
  getDefaultLocationSourceCapabilities,
  getLegacyLocationSelection,
  getPrimaryLocationLabel,
  getSourceLocationPlan,
  isLocationSourceCompatible,
  LOCATION_GEO_SCOPE_VALUES,
  LOCATION_GEO_SCOPE_VALUES as GEO_SCOPE_VALUES,
  LOCATION_INPUT_MODE_VALUES,
  LOCATION_MATCH_STRICTNESS_VALUES,
  LOCATION_SEARCH_SCOPE_VALUES,
  LOCATION_WORKPLACE_TYPE_VALUES,
  type LocationEvidence,
  type LocationEvidenceEntry,
  type LocationEvidenceEntryKind,
  type LocationEvidenceInput,
  type LocationEvidenceQuality,
  type LocationGeoScope,
  type LocationInputMode,
  type LocationIntent,
  type LocationIntentInput,
  type LocationMatchResult,
  type LocationMatchStrictness,
  type LocationPlanResult,
  type LocationProximity,
  type LocationSearchScope,
  type LocationSourceCapabilities,
  type LocationSourceCapabilitiesInput,
  type LocationSourcePlan,
  type LocationWorkplaceType,
  matchLocationIntent,
  normalizeLocationCountryKey,
  normalizeLocationEvidence,
  normalizeLocationGeoScope,
  normalizeLocationIntent,
  normalizeLocationMatchStrictness,
  normalizeLocationSearchScope,
  normalizeLocationSourceCapabilities,
  normalizeLocationWorkplaceType,
  normalizeLocationWorkplaceTypes,
  planLocationSource,
  planLocationSources,
  summarizeLocationIntent,
} from "../location-domain.js";

export type GeoScope = LocationGeoScope;
export type WorkplaceType = LocationWorkplaceType;
export type SourceLocationCapabilities = LocationSourceCapabilities;
export type SourceLocationPlan = LocationSourcePlan;
export type LocationMatchStrength = LocationMatchStrictness;
